# Random Tensor

Why random tensors?

Random tensors are important becouse the way many neural networks learn is that they start with tensors full of random numbers and the adjust those Random numbers to better represent the data.

 start with random numbers -> look at the data -> update the random numbers ->Look at the data -> update random numbers
Torch random Tesnors- https://pytorch.org/docs/stable/generated/torch.rand.html

In [71]:
import torch    
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 


In [72]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4486, 0.5919, 0.1738, 0.2224],
        [0.8688, 0.2222, 0.8358, 0.9663],
        [0.5563, 0.1340, 0.3377, 0.9547]])

In [73]:
random_image_size_tensor = torch.rand(3, 224, 224)#height , width , colour chnals(R<G<B))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [74]:
print(torch. __version__)

2.4.1+cu124


In [75]:
torch.cuda.is_available()

True

In [76]:
var1 = torch.FloatTensor([1.0,2.0,3.0]).cuda()
var1

tensor([1., 2., 3.], device='cuda:0')

In [77]:
var1.device

device(type='cuda', index=0)

### Zeros and Ones

In [78]:
#create a tensor of zeros
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [79]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [80]:
# Create a tensor of Ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [81]:
ones.dtype

torch.float32

### Creating a range of tensors and Tensors-Like

In [82]:
# use torch.range
one_to_ten = torch.arange(1,11) 
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
#using steps methods
one_to_hunderd = torch.arange(start = 1, end = 100, step = 5)
one_to_hunderd

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [84]:
#Creating tesnor Like
Ten_zeros = torch.zeros_like(one_to_ten) # same shape as one_to_ten
Ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes


In [85]:
# float 32 tensor 
float_32_1_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,) # defaults to None)
float_32_1_tensor 

tensor([3., 6., 9.])

In [86]:
float_32_1_tensor.dtype


torch.float32

In [87]:
# float 32 tensor 
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [88]:
float_32_tesnor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device = "cuda", # what device is your tensor on (none for cpu)
                               requires_grad=False) # whether or not to track gradients with this tensor opertaion(for now)
                               

float_32_tesnor

tensor([3., 6., 9.], device='cuda:0')

##### tensor dataype
**note:** tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning

**1.** tensor not right datatype

**2.** tesnor not right shape

**3.** tensor not on the right device

In [89]:
#how to change the datatype
float_16_tensor = float_32_tesnor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

##### link for the pytorch datatype documentation
https://pytorch.org/docs/stable/tensors.html

In [90]:
#what happens
float_16_tensor * float_32_tesnor

tensor([ 9., 36., 81.], device='cuda:0')

In [91]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32,
                             device ="cuda",
                             requires_grad = False)
int_32_tensor

tensor([3, 6, 9], device='cuda:0', dtype=torch.int32)

In [92]:

float_32_tesnor*int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

##### Getting the information from tensor 

**1.** tensor not right datatype - to do go get datatype from a tensor, can use `tesnor.dtype`

**2.** tesnor not right shape - to get shape from a tensor, can use `tensor.shape`

**3.** tensor not on the right device - to get deivr from a tensor, can use `tensor.device`

In [93]:
#create a tensor 
some_tensor = torch.rand((3,4),dtype = torch.float32, device = "cuda", requires_grad = False)
some_tensor

tensor([[0.3906, 0.3526, 0.5042, 0.1629],
        [0.3441, 0.0301, 0.6208, 0.7103],
        [0.5688, 0.4651, 0.7688, 0.9069]], device='cuda:0')

In [94]:
#find out the details about some_tensor
print(f"Datatype of some_tensor: {some_tensor.dtype}")
print(f"Shape of some_tensor: {some_tensor.shape}")
print(f"Device of some_tensor: {some_tensor.device}")

Datatype of some_tensor: torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device of some_tensor: cuda:0


In [95]:
#create a tensor1
some_tensor1 = torch.rand(3,4)
some_tensor1

tensor([[0.5859, 0.8477, 0.2518, 0.5253],
        [0.4239, 0.2930, 0.7918, 0.2411],
        [0.0368, 0.2740, 0.6924, 0.4087]])

In [96]:
#find out the details about some_tensor
print(f"Datatype of some_tensor: {some_tensor1.dtype}")
print(f"Shape of some_tensor: {some_tensor1.shape}")
print(f"Device of some_tensor: {some_tensor1.device}")

Datatype of some_tensor: torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device of some_tensor: cpu


#### Manipulating Tensor (tensor operation)

Tensor opertations includes:

**1.** Addition

**2.** Subtration

**3.** Multiplication(element - wise)

**4.** Division 

**5.** Matrix multiplication

In [97]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [98]:
#multiplication tenor with 10
tensor*10

tensor([10, 20, 30])

In [99]:
#subtration 10
tensor -10

tensor([-9, -8, -7])

In [100]:
# Try out Pytorch in_built function
# torch.add
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matric multiplication

Tow main ways of performing multiplication in nerural network and deeplearning 

**1.** Element- wise multiplication

**2.** Matrix multiplication (dot product )

`There are tow main rules that performing matrix multiplication need to satisy:`

**1.** The `inner dimension` must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
* **note** @ represent dot product like matrix multiplication

**2.** The resulting matrix has the shape of `outer dimensions`
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [101]:
#Element Wise Multiplication
print( tensor,"*",tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [102]:
# Matrix multiplication 
torch.matmul(tensor,tensor) #dot product 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [103]:
# Matrix multiplication by hand
%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

CPU times: total: 0 ns
Wall time: 0 ns
tensor(14)


In [104]:
%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [105]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.1019, 0.2977],
        [0.2997, 1.3543]])

### Use this for your experiments
https://matrixmultiplication.xyz/

In [106]:
tensor_A = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])
tensor_B = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])
#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

`RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)`

In [107]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues , we can manipulate the shape of the tensor using a `transpose`

A `transpose` switches the axes or dimensions of given tensor

In [108]:
print(tensor_B.T)
tensor_B.T.shape

tensor([[ 7,  8,  9],
        [10, 11, 12]])


torch.Size([2, 3])

In [109]:
print(tensor_B)
tensor_B.shape

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


torch.Size([3, 2])

##### as you can see that the transpose change the dimension of the matrix but not the elements so it will effect the dimensions of the matrix but not the result or the output of the data set
`T` represent `transpose`

In [110]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### finding the min, max, mean, sum, etc(tensor aggregation)



In [111]:
#create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [112]:
#find the min
torch.min(x), x.min(), x.max()

(tensor(1), tensor(1), tensor(91))

`RuntimeError `                             Traceback (most recent call last)
`Cell In[45], line 1`
`----> 1 torch.mean(x)`

``RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long``

In [113]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work

(tensor(46.), tensor(46.))

In [114]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### **Finding the positional min and max**

In [115]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [116]:
#find the positional in tesnor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [117]:
x[0]

tensor(1)

In [118]:
#find the positional in tesnor that has the maximum value with argmax() -> returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

In [119]:
x[9]

tensor(91)

# **Reshaping, Stacking, Squeezing and Unsqueezing tensors**

**Reshaping** - `reshapes an input tensor to a defined shape`

**View** - `Return a view of an input tensor of certain shape but keep the same memory as the original tensor `

**Stacking** - `combine multiple tensor on top of each other (vstack) or side by side(hstack)`*https://pytorch.org/docs/stable/generated/torch.stack.html*

   ###**(vstake)** - *https://pytorch.org/docs/stable/generated/torch.vstack.html*

   ###**(hstack)** - *https://pytorch.org/docs/stable/generated/torch.hstack.html*

**Squeeze** -`remove all` 1 `dimension from a tensor`

**Unsqueeze** - `add a` 1 `dimension to a target tensor`

**Permute** - `Return a view of the input with dimensions permuted (swapped) in certain way`

In [120]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [121]:
# add an extra dimension
#x_reshaped = x.reshape(1,7)
#x_reshaped, x_reshaped.shape
#/---------------------------------------------------------------------------
#RuntimeError                              Traceback (most recent call last)
#Cell In[52], line 2
#     1 # add an extra dimension
#--> 2 x_reshaped = x.reshape(1,7)
#   3 x_reshaped, x_reshaped.shape

#RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [122]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [123]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [124]:
#change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [125]:
#changing z changes x(because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [126]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x],dim=0)
x_stacked 

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [127]:
#squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_reshaped = x_reshaped.squeeze()
print(f"\nNew tensor: {x_reshaped}")
print(f"\nNew shape: {x_reshaped.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [128]:
# torch.unqueeze() - adds a single dimension to a target tensor at a specified dimension
print(f"Previous Target: {x_stacked}")
print(f"Previous shape: {x_stacked.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed = x_stacked.unsqueeze(dim=2)
print(f"\nNew Target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous Target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([3, 9])

New Target: tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]],

        [[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]],

        [[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])
New shape: torch.Size([3, 9, 1])


In [129]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(0, 2, 1) # shifts axis 0->1, 1->2, 2->0)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [height, colour_channels, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([224, 3, 224])


In [130]:
x_original[ 0, 0 :]

tensor([[5.3469e-01, 7.2100e-01, 2.0429e-01],
        [7.8787e-01, 6.8404e-01, 8.5688e-01],
        [6.9186e-01, 8.5506e-01, 1.6372e-01],
        [7.5847e-01, 3.4303e-01, 2.7261e-01],
        [5.0040e-01, 5.8201e-01, 4.0344e-01],
        [3.2129e-01, 5.9817e-01, 6.4721e-01],
        [1.9968e-01, 4.7186e-01, 5.8595e-01],
        [3.9441e-01, 5.8991e-01, 3.1996e-01],
        [2.2566e-01, 8.9507e-02, 7.4718e-01],
        [4.8118e-01, 6.2667e-01, 7.6498e-01],
        [4.5287e-01, 6.9337e-01, 6.7011e-01],
        [1.4814e-01, 5.8685e-01, 2.0759e-01],
        [4.3926e-01, 9.5840e-01, 7.6236e-01],
        [3.3729e-01, 5.5950e-01, 7.1816e-01],
        [2.7814e-01, 5.3569e-01, 2.4331e-01],
        [1.3319e-01, 5.7277e-01, 2.5378e-01],
        [1.7519e-01, 5.6313e-01, 5.8220e-01],
        [5.2472e-01, 6.3464e-01, 2.0257e-01],
        [7.7857e-01, 2.5694e-01, 5.6789e-01],
        [1.6685e-01, 8.7140e-01, 2.9835e-01],
        [7.6879e-01, 4.9997e-02, 1.0229e-01],
        [7.7882e-01, 9.1753e-01, 4

`https://pytorch.org/docs/stable/generated/torch.permute.html` **for torch.permute**

In [131]:
x_original[0, 0, 0] = 1
x_original

tensor([[[1.0000, 0.7210, 0.2043],
         [0.7879, 0.6840, 0.8569],
         [0.6919, 0.8551, 0.1637],
         ...,
         [0.1190, 0.0754, 0.7903],
         [0.1427, 0.4465, 0.1646],
         [0.8549, 0.9418, 0.8996]],

        [[0.6502, 0.7327, 0.3314],
         [0.8788, 0.4467, 0.0039],
         [0.4634, 0.1263, 0.5258],
         ...,
         [0.1911, 0.5598, 0.1992],
         [0.8329, 0.9450, 0.2317],
         [0.9173, 0.6533, 0.7520]],

        [[0.4954, 0.5092, 0.8199],
         [0.5710, 0.1780, 0.0274],
         [0.7527, 0.8100, 0.7292],
         ...,
         [0.6487, 0.7977, 0.3504],
         [0.0925, 0.9707, 0.9956],
         [0.0998, 0.5096, 0.0643]],

        ...,

        [[0.5405, 0.6423, 0.9145],
         [0.4198, 0.0413, 0.5250],
         [0.7430, 0.8136, 0.5015],
         ...,
         [0.7168, 0.0370, 0.9119],
         [0.5443, 0.5318, 0.1368],
         [0.0810, 0.5558, 0.3699]],

        [[0.8906, 0.5276, 0.8182],
         [0.1692, 0.2302, 0.5219],
         [0.

In [132]:
x_original[0, 0, 0] = 1
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(1.), tensor(1.))

### **Indexing (selecting data from tensors)**

indexing with Pytorch is very similar to Numpy

In [133]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [134]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [135]:
#lets index on the middle bracket
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [136]:
#lets index ont the most inner bracket(last bracket)
x[0, 2, 2]

tensor(9)

In [137]:
#you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [138]:
#get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [139]:
#get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [140]:
print(x[0,2,2])
print(x[0, 0,2 ])

tensor(9)
tensor(3)


### **Pytorch Tensor & Numpy**

`Numpy is a popular scientific Python numerical computing Library.`
`And becouse of this, Pytorch has functionality to interact with it`

* **Data in Numpy, want in Pytorch Tensor**-> `torch.from_numpy(ndarray)`
* **Pytorch Tensor -> Numpy** -> `torch.Tesnor.numpy()`


In [141]:
import numpy as np

In [142]:
array = np.arange(1.0, 8.0)
tesnor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of 'float64' unless specified otherwise
tesnor ,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [143]:
tesnor.dtype

torch.float64

In [144]:
tesnor.dtype

torch.float64

In [145]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [146]:
#Change the value of array , what will this to do in tesnor?
array = array + 1
array, tesnor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [147]:
#Tesnor to Numpy array
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [148]:
numpy_tensor.dtype

dtype('float32')

In [149]:
#change the tesnor , what will happen to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)

in short how a neural network learns:

`start with random numbers -> tesnor operations -> update random number to try and make them better representation of the data -> agian -> again ->again...`

**To reduce the randomness in neural network  and Pytorch comes the concept of a** **`random seed.`**

Essentially what the random seed does is `"flavour"` the randomness


In [150]:
#create tow random tensors 

random_tesnor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tesnor_A)
print(random_tensor_B)

print(random_tesnor_A == random_tensor_B)

tensor([[0.3716, 0.6546, 0.6110, 0.5990],
        [0.5981, 0.2696, 0.2781, 0.1545],
        [0.2127, 0.9911, 0.1848, 0.8769]])
tensor([[0.6916, 0.5753, 0.8417, 0.6976],
        [0.8682, 0.0127, 0.7293, 0.7531],
        [0.9262, 0.1456, 0.1954, 0.3142]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [151]:
# lets`s make some random but reproducible tensors

#set random seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)


tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**`Extra resources for Reproducibility`**

*https://pytorch.org/docs/stable/generated/torch.manual_seed.html*

*https://pytorch.org/docs/stable/notes/randomness.html*

### **Running tensor and Pytorch objects on the GPU's (and making fastre computations)**

Gpus= faster computation on numbers becouse of cuda (paparallel)

• Getting a GPU


In [152]:
torch.cuda.is_available()

True

For pytorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:

https://pytorch.org/docs/stable/notes/cuda.html

E.g Run on `GPU` if available, else defoult to `CPU`

In [153]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

### 3• Putting tesnor (and models) on the `GPU`

The resons we want our tensor/model on the GPU becouse using a GPU results in faster computations.

In [154]:
#create a tensor (default on the CPU)
tesnor = torch.tensor([1,2,3])

#tensor not on GpU
print(tesnor,tesnor.device)

tensor([1, 2, 3]) cpu


In [155]:
# Move tesnor to GPU if available
tensor_on_gpu = tesnor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4• Moving tesnor to the CPU

(some times when you need to run the model of `numpy` that dosnt work on gpu so you need to switch between GPU to CPU vice versa)

In [156]:
# if tesnor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

`can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first`

In [157]:
#to fix the issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [158]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 6.2 Building a pytorch Linear model


In [159]:
#create a linear layer model by subclassing nn.Module
class LinearRegressionModelv2(nn.module):
    def __init__(self):
        super().__init__()
        # USe nn.linear() for creating the model parameters
        self.linear_layer = nn.linear(in_features = 1, out_features = 1)

    #def forward(self, x: torch.Tensor) -> torch.Tensor:

NameError: name 'nn' is not defined